DEBUG: "True"
ENVIRONMENT: "development"
MONGODB_URI: "mongodb+srv://arjundatt:bC9MKcKOzEeczNPT@tofai-cluster0.kpxoiil.mongodb.net/?appName"
DATABASE_NAME: "tofai"
REDIS_HOST: "redis-14879.c285.us-west-2-2.ec2.redns.redis-cloud.com"
REDIS_PORT: "14879"
REDIS_USER: "default"
REDIS_SECRET: "4oeDB6tc57n2RbA0r24XeO15Sos5r9rg"
AWS_ACCESS_KEY_ID: "AKIAYIA7EMAJPYDMQYG4"
AWS_SECRET_ACCESS_KEY: "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"
S3_REGION: "us-east-2"
GEMINI_API_PROJECT_NUMBER: "708610753332"
GEMINI_API_SECRET: "AIzaSyBoFa5vrNNniZhsKkZC_7UEGGBmP-8OuM4"
ELEVEN_TTS_SECRET: "sk_49e9eefa1a5ccbf3c1a106bb8a0f5d09f90394ab5dccb4ba"
GOOGLE_SEARCH_API_KEY: "AIzaSyA7pRnrDNnjaxI2ZKYXkvaDbWnqv1BWw1M"
GOOGLE_CSE_ID: "72c6a0d0518654d07"
COGNITO_REGION: "us-east-2"
COGNITO_USER_POOL_ID: "us-east-2_g2inm9tVS"
COGNITO_CLIENT_ID: "50blk932ao456njlosq6kfdr74"
COGNITO_CLIENT_SECRET: "425ca8dstct124ak7eapbha8lm4ojj0gmofou9km9evmjjnhn5o"
COGNITO_DOMAIN: "us-east-2g2inm9tvs"
COGNITO_REDIRECT_URL: "http://localhost:8000/api/auth/callback"
COGNITO_LOGOUT_URL: "http://localhost:8000"
COGNITO_SCOPE: "email openid phone"
COGNITO_TOKEN_SIGNING_URL: "https://cognito-idp.us-east-2.amazonaws.com/us-east-2_g2inm9tVS/.well-known/jwks.json"
SECRET_KEY: "development_secret_key"
CELERY_BROKER_URL: "redis://localhost:6379/1"
CELERY_RESULT_BACKEND: "redis://localhost:6379/1"
GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/708610753332/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
GCP_SERVICE_ACCOUNT: "github-actions-sa@sonorous-folio-458117-g5.iam.gserviceaccount.com"
