from fastapi import APIRouter, HTTPException, Depends, BackgroundTasks
from pydantic import BaseModel
from typing import Optional, List, Dict, Any, Union
from uuid import uuid4
from datetime import datetime

from services.storage.database import get_db
from services.ai.ai_orchestrator import AIOrchestrator

router = APIRouter()

# Initialize AI orchestrator
ai_orchestrator = AIOrchestrator()

class VideoResponse(BaseModel):
    """Model for video response."""
    video_url: str
    thumbnail_url: str
    duration: int
    format: str
    resolution: str

class JobStatusResponse(BaseModel):
    """Model for job status response."""
    message: str
    job_id: str
    status: str
    progress: Optional[int] = None

@router.post("/sessions/{session_id}/video", response_model=JobStatusResponse)
async def generate_video(
    session_id: str,
    parameters: Optional[Dict[str, Any]] = None,
    background_tasks: BackgroundTasks = None,
    db = Depends(get_db)
):
    """Generate final video by combining visuals and audio."""
    # Check if session exists and has visuals and audio
    session = await db.sessions.find_one({"id": session_id})
    
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    
    if not session.get("visuals"):
        raise HTTPException(status_code=400, detail="Visuals must be completed first")
    
    if not session.get("audio"):
        raise HTTPException(status_code=400, detail="Audio must be completed first")
    
    # Create a new job for video generation
    job_id = f"video-{session_id}-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
    job = {
        "id": job_id,
        "session_id": session_id,
        "type": "video",
        "status": "processing",
        "progress": 0,
        "created_at": datetime.utcnow(),
        "parameters": parameters or {}
    }
    
    await db.jobs.insert_one(job)
    
    # Run the AI orchestrator to generate video
    try:
        result = await ai_orchestrator.run(session_id, current_step="audio")
        
        if not result["success"]:
            # Update job status
            await db.jobs.update_one(
                {"id": job_id},
                {
                    "$set": {
                        "status": "failed",
                        "progress": 0,
                        "completed_at": datetime.utcnow(),
                        "error": result.get("error", "Unknown error")
                    }
                }
            )
            
            return {
                "message": f"Video generation failed: {result.get('error', 'Unknown error')}",
                "job_id": job_id,
                "status": "failed",
                "progress": 0
            }
        
        # Get updated session
        updated_session = await db.sessions.find_one({"id": session_id})
        
        # If no video was generated by orchestrator, create a placeholder
        if not updated_session.get("video"):
            # Create a placeholder video response
            video_data = {
                "videoUrl": f"/api/placeholder/video/{session_id}",
                "thumbnailUrl": f"/api/placeholder/thumbnail/{session_id}",
                "duration": 30,
                "format": "mp4",
                "resolution": "720p"
            }
            
            # Update session with placeholder video data
            await db.sessions.update_one(
                {"id": session_id},
                {
                    "$set": {
                        "video": video_data,
                        "updated_at": datetime.utcnow(),
                        "current_step": "completed",
                        "status": "completed"
                    }
                }
            )
        else:
            video_data = updated_session.get("video")
        
        # Update job status
        await db.jobs.update_one(
            {"id": job_id},
            {
                "$set": {
                    "status": "completed",
                    "progress": 100,
                    "completed_at": datetime.utcnow(),
                    "result": video_data
                }
            }
        )
        
        return {
            "message": "Video generation completed",
            "job_id": job_id,
            "status": "completed",
            "progress": 100
        }
        
    except Exception as e:
        # Update job status
        await db.jobs.update_one(
            {"id": job_id},
            {
                "$set": {
                    "status": "failed",
                    "progress": 0,
                    "completed_at": datetime.utcnow(),
                    "error": str(e)
                }
            }
        )
        
        return {
            "message": f"Video generation failed: {str(e)}",
            "job_id": job_id,
            "status": "failed",
            "progress": 0
        }

@router.get("/sessions/{session_id}/video", response_model=Union[VideoResponse, JobStatusResponse])
async def get_video(session_id: str, db = Depends(get_db)):
    """Get generated video or job status if generation is in progress."""
    session = await db.sessions.find_one({"id": session_id})
    
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    
    if not session.get("video"):
        # Check if there's a job in progress
        job = await db.jobs.find_one({
            "session_id": session_id,
            "type": "video",
            "status": {"$in": ["pending", "processing"]}
        })
        
        if job:
            return {
                "message": "Video generation in progress",
                "job_id": job["id"],
                "status": job["status"],
                "progress": job.get("progress", 0)
            }
        else:
            raise HTTPException(status_code=404, detail="Video not found")
    
    # Format and return video
    video_data = session["video"]
    
    return {
        "video_url": video_data.get("videoUrl", video_data.get("video_url")),
        "thumbnail_url": video_data.get("thumbnailUrl", video_data.get("thumbnail_url")),
        "duration": video_data.get("duration", 0),
        "format": video_data.get("format", "mp4"),
        "resolution": video_data.get("resolution", "720p")
    }