"""
Config-driven framework for AI orchestration.
This module defines Pydantic models for the workflow steps and prompt generation.
NO_AI_CODE=True
"""
from pydantic import BaseModel, Field, model_validator
from typing import List, Dict, Optional, Union, Any, Literal, Type
from enum import Enum
from services.ai.agents.agents_list import AgentId

class OutputModality(str, Enum):
    """
    Enum for supported output modalities of prompts.
    """
    TEXT = "TEXT"
    IMAGE = "IMAGE"
    AUDIO = "AUDIO"
    SPEECH = "SPEECH"
    MUSIC = "MUSIC"
    VIDEO = "VIDEO"


class FewShot(BaseModel):
    """
    Model for few-shot examples used in prompts.
    Each few-shot example contains a list of options that serve as examples
    for language models to better understand the expected response format.
    
    Args:
        options (List[str]): A list of example options that demonstrate the 
            expected format and content for responses. Defaults to an empty list.
    """
    options: List[str] = Field(default_factory=list)


class Ingridient(BaseModel):
    """Model for a single ingridient used in the screenplay.
    
    Args:
        name (str): Unique name of the ingridient.
        prompt (str): Detailed description for the ingridient. This is the prompt to be used by the LLM to generate the ingridient. Take into account the ethnicity and geography to describe any characters.
        type (Literal["character", "object", "environment", "background_music"]): Type of the ingridient. Can be one of: character, object, environment, background_music.
        min_scene_occurrences (Optional[int]): Minimum number of scenes the ingredient must appear in to be listed.
        dependencies (List[str]): List of ingridients' names which this ingridient visually depends on. For example, if a portrait of John Doe would depend on the character John Doe.
    """
    name: str = Field(..., description="Unique name of the ingridient.")
    prompt: str = Field(..., description="""Detailed description for the ingridient. This is the prompt to be used by the LLM to generate the ingridient. 
                        Key points to consider:
                        * Take into account the ethnicity and geography to describe any characters.
                        * For objects, describe the object in detail, including its appearance, function, and any relevant context.
                        * For environments, describe the location, geography, atmosphere, and any significant features like backdrop, etc.
                        * For background music, use the provided prompt.""")
    type: Literal["character", "object", "environment", "background_music"] = Field(..., description="Type of the ingridient. Can be one of: character, object, environment, background_music.")
    min_scene_occurrences: Optional[int] = Field(..., description="Minimum number of scenes the ingredient must appear in to be listed.")
    dependencies: List[str] = Field(..., description="List of ingridients' names which this ingridient visually depends on. For example, if a portrait of John Doe would depend on the character John Doe.")

class Scene(BaseModel):
    """Model for a single scene in the screenplay.
    Args:
        title (str): Title of the scene.
        plot (str): Plot of the scene.
        characters_name (List[str]): Distinct list of characters' names that appear in the scene. Must be subset of common_ingridients.
        objects_name (List[str]): Distinct list of objects' names in the scene. Must be subset of common_ingridients.
        environments_name (List[str]): List of environmental elements' names in the scene. Must be subset of common_ingridients.
        narration (str): Voiceover prompt for the scene.
        cinematography_name (str): Cinematography/Video prompt for the scene.
    """
    title: str = Field(..., description="Title of the scene")
    plot: str = Field(..., description="Plot of the scene")
    characters_name: List[str] = Field(..., description="Distinct list of characters' names that appear in the scene. Must be subset of common_ingridients.")
    objects_name: List[str] = Field(..., description="Distinct list of objects' names in the scene. Must be subset of common_ingridients.")
    environment_name: str = Field(..., description="Environmental element's name in the scene. Must be subset of common_ingridients.")
    narration: str = Field(..., description="Voiceover prompt for the scene.")
    cinematography_name: str = Field(..., description="Video prompt for the scene.")

class Screenplay(BaseModel):
    """Model for the screenplay generated by the framework.
    Args:
        common_ingridients (List[Ingridient]): Distinct list of ingridients (characters, objects, environments) used in the screenplay across multiple scenes.
        scenes (List[Scene]): List of scenes in the screenplay.
    """
    common_ingridients: List[Ingridient] = Field(..., description="""Distinct list of common ingridients (characters, objects, environments) used in the screenplay across multiple scenes.
                                                 characters - are the people/animals that visually appeat in any scene,
                                                 objects - are the non-living objects that visually appear in atleast more than one scene and are important to the story. Don't include objects that are not important to the story, like furniture, etc, or appear in a single scene.
                                                 environments - are the locations that visually appear in atleast more than one scene. Don't include locations that appear in a single scene.""")
    scenes: List[Scene] = Field(..., description="Chronologically ordered list of scenes in the screenplay")

class MultipleTextOutputSchema(BaseModel):
    """Model for the schema of options returned for a framework step.
    Args:
        outputs (List[str]): List of outputs.
    """
    outputs: List[str]

    @model_validator(mode="after")
    def validate_outputs(self):
        if not self.outputs:
            raise ValueError("Outputs cannot be empty.")
        return self

class Prompt(BaseModel):
    """
    Model for prompt configuration used to generate structured prompts for language models.
    Defines all components needed to create a complete prompt with proper formatting.
    
    Args:
        id (str): Unique identifier for the prompt configuration.
        prefix (str): The main text content of the prompt that comes before examples.
        few_shots (List[FewShot]): List of few-shot examples to include in the prompt.
            Defaults to an empty list.
        options_delimiter (str): The string used to separate multiple options in the 
            language model's response. Defaults to "||".
        option_count (int): The number of options to request from the language model.
            Defaults to 3.
        parameters (List[str]): List of parameter names that need to be included in the 
            prompt template. Defaults to an empty list.
        output_instruction (Optional[str]): Explicit instructions for the expected 
            output format. If not provided, uses a default instruction based on 
            option_count and options_delimiter.
        expected_output_modality (OutputModality): The expected output modality of the prompt
            (TEXT, IMAGE, or AUDIO). Defaults to TEXT.
        expected_output_schema: Pydantic model schema that the output
            should be structured as.
    """
    id: str
    ignore_prompt_base: bool = False
    prefix: str
    few_shots: List[FewShot] = Field(default_factory=list)
    options_delimiter: str = "||"
    option_count: int = 3
    parameters: List[str] = Field(default_factory=list)
    params_format: Literal["dict", "list"] = "dict"
    output_instruction: Optional[str] = f"Give me {option_count} options, add `{options_delimiter}` between the options. Do not output anything else."
    expected_output_modality: OutputModality = OutputModality.TEXT
    expected_output_schema: Union[str, None] = None

class AgentStep(BaseModel):
    id: AgentId
    parameters: List[str]

class FrameworkStep(BaseModel):
    """
    Model for a step in the AI workflow framework. Represents a single stage in
    a multi-step process where each step can contain multiple prompts and defines
    transition logic to subsequent steps.
    
    Args:
        id (str): Unique identifier for the step.
        name (str): Human-readable name for the step.
        description (str): Detailed explanation of what this step accomplishes.
        prompts (List[Prompt]): List of prompt configurations to be used in this step.
        next_step (Optional[str]): Identifier of the step to transition to after 
            this one completes. If None, this is a terminal step. Defaults to None.
        requires_user_input (bool): Flag indicating whether this step requires 
            input from the user before proceeding. Defaults to False.
    """
    id: str
    name: str
    description: str
    expected_selection_count: Union[int, Literal["ALL"]] = 1
    prompts: List[Prompt]
    agents: List[AgentStep] = []
    next_step: Optional[str] = None
    requires_user_input: bool = False
    require_user_input_for_step_id: str = ""
    result_display_allowed: bool = True
    version: int = 0
    

class Framework(BaseModel):
    """
    Model for the overall framework configuration. Defines a complete workflow with
    multiple steps, including starting and ending points, and global configuration
    that applies across all steps.
    
    Args:
        id (str): Unique identifier for the framework.
        name (str): Human-readable name for the framework.
        description (str): Detailed explanation of the framework's purpose and functionality.
        steps (List[FrameworkStep]): List of all steps in the framework workflow.
        initial_step (str): Identifier of the first step to execute in the workflow.
        final_step (str): Identifier of the step that marks the completion of the workflow.
        prompt_base (str): Common prefix text to be included in all prompts across
            the framework. Defines the overall persona and context for the language model.
            Defaults to a marketing/storytelling expert persona.
    """
    id: str
    name: str
    description: str
    steps: List[FrameworkStep]
    initial_step: str
    final_step: str
    prompt_base: str = """You are the best marketer on Earth specifically specialising in video storytelling that helps brands get reach on social media. You are weird like Vsauce, thorough like Veritasium, goofy and imaginative like Tim Urban, and can write copy like David Ogilvy. You do this by understanding what kind of content the brands want by taking them through a series of steps mentioned below, providing them a few options at each step, and then on the basis of the user's reply, proceeding to the next step. Your scripts are written in such a way to have some stimulation every 3-5 seconds."""

class MediaUri(BaseModel):
    uri: str

class ResultOptions(BaseModel):
    """Model for the resulting options given by one prompt.
    Args:
        result_options (List[Union[str, bytes]]): the one or more options given as a result of a single prompt.
        context_ids (List[str]): the context id (hash) of each option.
        selected_option (int): the option selected by user, or 0 if len(result_options)=1
    """
    result_options: List[Union[str, MediaUri]]
    context_ids: List[str]
    selected_option: int = -1

    @model_validator(mode="after")
    def validate_result_options_and_context_ids(self):
        result_options = self.result_options
        context_ids = self.context_ids
        if len(result_options) != len(context_ids):
            raise ValueError("The length of result_options must be the same as the length of context_ids.")
        return self
    
class StepResult(BaseModel):
    """Model for the result of a step.
    Args:
        versioned_results (Dict[str, List[ResultOptions]]): Dict of version to result of a step corresponding to a path of selections done for previous steps.
    """
    versioned_results: Dict[str, List[ResultOptions]] = Field(
        default_factory=dict,
        description="Dict of version to result of a step corresponding to a path of selections done for previous steps."
    )
        
class FrameworkStepResult(BaseModel):
    """Model for the result of a step.
    Args:
        id (str): Id of the step.
        result (StepResult): result of each prompt/agent in the step, in that order.
    """
    id: str
    result: StepResult | List[ResultOptions]
    display_to_user: bool = True

class FrameworkResult(BaseModel):
    """Model for the results of executing the framework.
    Args:
        id (str): Id of the framework.
        step_results (List[FrameworkStepResult]): result of each step.
    """
    id: str
    step_results: List[FrameworkStepResult]
